Checking out-of-disk-space condition. Safer failures.

diff --git a/src/sdk-manage b/src/sdk-manage
--- a/src/sdk-manage
+++ b/src/sdk-manage
@@ -143,15 +143,30 @@ install_target() {
     fi
 
     mkdir /fuck_hardlinks/
+    if [ $? -ne 0 ]; then echo "Couldn't create /fuck_hardlinks/ directory. Delete it if it already exists, and make sure this script has right to create it."; return 6; fi
     cd /fuck_hardlinks/
+    if [ $? -ne 0 ]; then echo "Couldn't enter /fuck_hardlinks/ directory. This shouldn't happen :)"; return 7; fi
 
     echo Decompressing target
     tar jxf /srv/mer/targets/$name.tar.bz2 
+    
+    if [ $? -ne 0 ]; then
+	if [ "$( df --sync / | tr -s ' ' | tail -n 1 | cut -d ' ' -f 4 )" -lt 10000 ]; then
+	    echo "Not enough disk space to unpack target image"
+	else
+	    echo "Couldn't unpack target image"
+	fi
+	rm -rf /fuck_hardlinks/
+	return 4
+    fi
 
     echo Relocating target
     mkdir /srv/mer/targets/$name
+    if [ $? -ne 0 ]; then  rm -rf /fuck_hardlinks/; echo "Couldn't create target directory, aborting."; return 5; fi
     rsync -a /fuck_hardlinks/ /srv/mer/targets/$name/
+    if [ $? -ne 0 ]; then  echo "Rsync didn't exactly run as intended, expect problems."; fi
     chown -R mersdk /srv/mer/targets/$name
+    if [ $? -ne 0 ]; then  echo "Chown of target dir failed, your target may not work properly."; fi
 
     rm -rf /fuck_hardlinks/
     rm /srv/mer/targets/$name.tar.bz2
